# Generated by Django 5.0 on 2023-12-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BingoSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number1", models.IntegerField()),
                ("number2", models.IntegerField()),
                ("number3", models.IntegerField()),
                ("number4", models.IntegerField()),
                ("number5", models.IntegerField()),
                ("number6", models.IntegerField()),
                ("number7", models.IntegerField()),
                ("number8", models.IntegerField()),
                ("number9", models.IntegerField()),
                ("number10", models.IntegerField()),
                ("number11", models.IntegerField()),
                ("number12", models.IntegerField()),
                ("number13", models.IntegerField()),
                ("number14", models.IntegerField()),
                ("number15", models.IntegerField()),
            ],
        ),
    ]
